---
title: "analysis_journal_metadata"
format: html
editor: visual
---

<!--# Hey bestie, before submitting the final version -> ctrl + f: 'NOTE' to check if all notes are evaluated and removed -->

## Version Control

```{r}
renv::restore()

library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(stringr)
library(purrr)
library(writexl)
library(openxlsx)
```

### Loading the data

Loading the files containing the metadata and inclusion decisions per article.

```{r}

###
# loading the data files
data_all_articles  <- read.xlsx(
  "all_articles_2023_2024_finaldecisions.xlsx", 
  sheet = "All")

data_included_articles <- read.xlsx(
  "all_articles_2023_2024_finaldecisions.xlsx",
  sheet = "Final mailinglist")
```

## Descriptives journal/inclusion data

```{r}

# Table with descriptives about article inclusions per journal
summary_table <- data_all_articles %>%
  group_by(Source.Title) %>%
  summarise(
    total = n(),
    included = sum(included, na.rm = TRUE),
    percentage = round((included/total)*100, digits = 2)
  )

####
# Adding for how many articles an invitation was sent out

# Step 1: joining datasets to count the number of invited articles per journal

invited_counts <- data_included_articles %>%
  left_join(data_all_articles %>% select(DOI, Source.Title), by = "DOI") %>%
  count(Source.Title, name = "invited")

# Step 2: combining it with the information in the other table

# NOTE: step 1 is not correct yet, because I want the non-bounced invitations not all the invitations that were sent. Bounces true/false variable is included in the dataset.

```
